export const CATEGORY_DATA = [
  {
    id: '1',
    name: 'Home',
    icon: 'home',
    bgColor: '#ffeb3b',
  },
  {
    id: '2',
    name: 'Work',
    icon: 'work',
    bgColor: '#4caf50',
  },
  {
    id: '3',
    name: 'School',
    icon: 'school',
    bgColor: '#2196f3',
  },
  {
    id: '4',
    name: 'Fitness',
    icon: 'fitness_center',
    bgColor: '#ff5722',
  },
  {
    id: '5',
    name: 'Travel',
    icon: 'flight',
    bgColor: '#9c27b0',
  },
  {
    id: '6',
    name: 'Shopping',
    icon: 'shopping_cart',
    bgColor: '#e91e63',
  },
  {
    id: '7',
    name: 'Finance',
    icon: 'account_balance',
    bgColor: '#009688',
  },
  {
    id: '8',
    name: 'Music',
    icon: 'music_note',
    bgColor: '#673ab7',
  },
  {
    id: '9',
    name: 'Health',
    icon: 'local_hospital',
    bgColor: '#f44336',
  },
  {
    id: '10',
    name: 'Food',
    icon: 'restaurant',
    bgColor: '#ff9800',
  },
  {
    id: '11',
    name: 'Education',
    icon: 'book',
    bgColor: '#3f51b5',
  },
  {
    id: '12',
    name: 'Technology',
    icon: 'devices',
    bgColor: '#00bcd4',
  },
  {
    id: '13',
    name: 'Entertainment',
    icon: 'movie',
    bgColor: '#8bc34a',
  },
  {
    id: '14',
    name: 'Communication',
    icon: 'message',
    bgColor: '#795548',
  },
  {
    id: '15',
    name: 'News',
    icon: 'article',
    bgColor: '#607d8b',
  },
  {
    id: '16',
    name: 'Automobile',
    icon: 'directions_car',
    bgColor: '#cddc39',
  },
  {
    id: '17',
    name: 'Photography',
    icon: 'camera_alt',
    bgColor: '#ffeb3b',
  },
  {
    id: '18',
    name: 'Gaming',
    icon: 'sports_esports',
    bgColor: '#4caf50',
  },
  {
    id: '19',
    name: 'Real Estate',
    icon: 'location_city',
    bgColor: '#2196f3',
  },
  {
    id: '20',
    name: 'Pets',
    icon: 'pets',
    bgColor: '#ff5722',
  },
];
