import { IIcon } from './icon-list.interface';

// export const ICONS_NAMESS = [
//   '3d_rotation',
//   'ac_unit',
//   'access_alarm',
//   'access_alarms',
//   'access_time',
//   'accessibility',
//   'accessible',
//   'account_balance',
//   'account_balance_wallet',
//   'account_box',
//   'account_circle',
//   'adb',
//   'add',
//   'add_a_photo',
//   'add_alarm',
//   'add_alert',
//   'add_box',
//   'add_circle',
//   'add_circle_outline',
//   'add_location',
//   'add_shopping_cart',
//   'add_to_photos',
//   'add_to_queue',
//   'adjust',
//   'airline_seat_flat',
//   'airline_seat_flat_angled',
//   'airline_seat_individual_suite',
//   'airline_seat_legroom_extra',
//   'airline_seat_legroom_normal',
//   'airline_seat_legroom_reduced',
//   'airline_seat_recline_extra',
//   'airline_seat_recline_normal',
//   'airplanemode_active',
//   'airplanemode_inactive',
//   'airplay',
//   'airport_shuttle',
//   'alarm',
//   'alarm_add',
//   'alarm_off',
//   'alarm_on',
//   'album',
//   'all_inclusive',
//   'all_out',
//   'android',
//   'announcement',
//   'apps',
//   'archive',
//   'arrow_back',
//   'arrow_downward',
//   'arrow_drop_down',
//   'arrow_drop_down_circle',
//   'arrow_drop_up',
//   'arrow_forward',
//   'arrow_upward',
//   'art_track',
//   'aspect_ratio',
//   'assessment',
//   'assignment',
//   'assignment_ind',
//   'assignment_late',
//   'assignment_return',
//   'assignment_returned',
//   'assignment_turned_in',
//   'assistant',
//   'assistant_photo',
//   'attach_file',
//   'attach_money',
//   'attachment',
//   'audiotrack',
//   'autorenew',
//   'av_timer',
//   'backspace',
//   'backup',
//   'battery_alert',
//   'battery_charging_full',
//   'battery_full',
//   'battery_std',
//   'battery_unknown',
//   'beach_access',
//   'beenhere',
//   'block',
//   'bluetooth',
//   'bluetooth_audio',
//   'bluetooth_connected',
//   'bluetooth_disabled',
//   'bluetooth_searching',
//   'blur_circular',
//   'blur_linear',
//   'blur_off',
//   'blur_on',
//   'book',
//   'bookmark',
//   'bookmark_border',
//   'border_all',
//   'border_bottom',
//   'border_clear',
//   'border_color',
//   'border_horizontal',
//   'border_inner',
//   'border_left',
//   'border_outer',
//   'border_right',
//   'border_style',
//   'border_top',
//   'border_vertical',
//   'branding_watermark',
//   'brightness_1',
//   'brightness_2',
//   'brightness_3',
//   'brightness_4',
//   'brightness_5',
//   'brightness_6',
//   'brightness_7',
//   'brightness_auto',
//   'brightness_high',
//   'brightness_low',
//   'brightness_medium',
//   'broken_image',
//   'brush',
//   'bubble_chart',
//   'bug_report',
//   'build',
//   'burst_mode',
//   'business',
//   'business_center',
//   'cached',
//   'cake',
//   'call',
//   'call_end',
//   'call_made',
//   'call_merge',
//   'call_missed',
//   'call_missed_outgoing',
//   'call_received',
//   'call_split',
//   'call_to_action',
//   'camera',
//   'camera_alt',
//   'camera_enhance',
//   'camera_front',
//   'camera_rear',
//   'camera_roll',
//   'cancel',
//   'card_giftcard',
//   'card_membership',
//   'card_travel',
//   'casino',
//   'cast',
//   'cast_connected',
//   'center_focus_strong',
//   'center_focus_weak',
//   'change_history',
//   'chat',
//   'chat_bubble',
//   'chat_bubble_outline',
//   'check',
//   'check_box',
//   'check_box_outline_blank',
//   'check_circle',
//   'chevron_left',
//   'chevron_right',
//   'child_care',
//   'child_friendly',
//   'chrome_reader_mode',
//   'class',
//   'clear',
//   'clear_all',
//   'close',
//   'closed_caption',
//   'cloud',
//   'cloud_circle',
//   'cloud_done',
//   'cloud_download',
//   'cloud_off',
//   'cloud_queue',
//   'cloud_upload',
//   'code',
//   'collections',
//   'collections_bookmark',
//   'color_lens',
//   'colorize',
//   'comment',
//   'compare',
//   'compare_arrows',
//   'computer',
//   'confirmation_number',
//   'contact_mail',
//   'contact_phone',
//   'contacts',
//   'content_copy',
//   'content_cut',
//   'content_paste',
//   'control_point',
//   'control_point_duplicate',
//   'copyright',
//   'create',
//   'create_new_folder',
//   'credit_card',
//   'crop',
//   'crop_16_9',
//   'crop_3_2',
//   'crop_5_4',
//   'crop_7_5',
//   'crop_din',
//   'crop_free',
//   'crop_landscape',
//   'crop_original',
//   'crop_portrait',
//   'crop_rotate',
//   'crop_square',
//   'dashboard',
//   'data_usage',
//   'date_range',
//   'dehaze',
//   'delete',
//   'delete_forever',
//   'delete_sweep',
//   'description',
//   'desktop_mac',
//   'desktop_windows',
//   'details',
//   'developer_board',
//   'developer_mode',
//   'device_hub',
//   'devices',
//   'devices_other',
//   'dialer_sip',
//   'dialpad',
//   'directions',
//   'directions_bike',
//   'directions_boat',
//   'directions_bus',
//   'directions_car',
//   'directions_railway',
//   'directions_run',
//   'directions_subway',
//   'directions_transit',
//   'directions_walk',
//   'disc_full',
//   'dns',
//   'do_not_disturb',
//   'do_not_disturb_alt',
//   'do_not_disturb_off',
//   'do_not_disturb_on',
//   'dock',
//   'domain',
//   'done',
//   'done_all',
//   'donut_large',
//   'donut_small',
//   'drafts',
//   'drag_handle',
//   'drive_eta',
//   'dvr',
//   'edit',
//   'edit_location',
//   'eject',
//   'email',
//   'enhanced_encryption',
//   'equalizer',
//   'error',
//   'error_outline',
//   'euro_symbol',
//   'ev_station',
//   'event',
//   'event_available',
//   'event_busy',
//   'event_note',
//   'event_seat',
//   'exit_to_app',
//   'expand_less',
//   'expand_more',
//   'explicit',
//   'explore',
//   'exposure',
//   'exposure_neg_1',
//   'exposure_neg_2',
//   'exposure_plus_1',
//   'exposure_plus_2',
//   'exposure_zero',
//   'extension',
//   'face',
//   'fast_forward',
//   'fast_rewind',
//   'favorite',
//   'favorite_border',
//   'featured_play_list',
//   'featured_video',
//   'feedback',
//   'fiber_dvr',
//   'fiber_manual_record',
//   'fiber_new',
//   'fiber_pin',
//   'fiber_smart_record',
//   'file_download',
//   'file_upload',
//   'filter',
//   'filter_1',
//   'filter_2',
//   'filter_3',
//   'filter_4',
//   'filter_5',
//   'filter_6',
//   'filter_7',
//   'filter_8',
//   'filter_9',
//   'filter_9_plus',
//   'filter_b_and_w',
//   'filter_center_focus',
//   'filter_drama',
//   'filter_frames',
//   'filter_hdr',
//   'filter_list',
//   'filter_none',
//   'filter_tilt_shift',
//   'filter_vintage',
//   'find_in_page',
//   'find_replace',
//   'fingerprint',
//   'first_page',
//   'fitness_center',
//   'flag',
//   'flare',
//   'flash_auto',
//   'flash_off',
//   'flash_on',
//   'flight',
//   'flight_land',
//   'flight_takeoff',
//   'flip',
//   'flip_to_back',
//   'flip_to_front',
//   'folder',
//   'folder_open',
//   'folder_shared',
//   'folder_special',
//   'font_download',
//   'format_align_center',
//   'format_align_justify',
//   'format_align_left',
//   'format_align_right',
//   'format_bold',
//   'format_clear',
//   'format_color_fill',
//   'format_color_reset',
//   'format_color_text',
//   'format_indent_decrease',
//   'format_indent_increase',
//   'format_italic',
//   'format_line_spacing',
//   'format_list_bulleted',
//   'format_list_numbered',
//   'format_paint',
//   'format_quote',
//   'format_shapes',
//   'format_size',
//   'format_strikethrough',
//   'format_textdirection_l_to_r',
//   'format_textdirection_r_to_l',
//   'format_underlined',
//   'forum',
//   'forward',
//   'forward_10',
//   'forward_30',
//   'forward_5',
//   'free_breakfast',
//   'fullscreen',
//   'fullscreen_exit',
//   'functions',
//   'g_translate',
//   'gamepad',
//   'games',
//   'gavel',
//   'gesture',
//   'get_app',
//   'gif',
//   'golf_course',
//   'gps_fixed',
//   'gps_not_fixed',
//   'gps_off',
//   'grade',
//   'gradient',
//   'grain',
//   'graphic_eq',
//   'grid_off',
//   'grid_on',
//   'group',
//   'group_add',
//   'group_work',
//   'hd',
//   'hdr_off',
//   'hdr_on',
//   'hdr_strong',
//   'hdr_weak',
//   'headset',
//   'headset_mic',
//   'healing',
//   'hearing',
//   'help',
//   'help_outline',
//   'high_quality',
//   'highlight',
//   'highlight_off',
//   'history',
//   'home',
//   'hot_tub',
//   'hotel',
//   'hourglass_empty',
//   'hourglass_full',
//   'http',
//   'https',
//   'image',
//   'image_aspect_ratio',
//   'import_contacts',
//   'import_export',
//   'important_devices',
//   'inbox',
//   'indeterminate_check_box',
//   'info',
//   'info_outline',
//   'input',
//   'insert_chart',
//   'insert_comment',
//   'insert_drive_file',
//   'insert_emoticon',
//   'insert_invitation',
//   'insert_link',
//   'insert_photo',
//   'invert_colors',
//   'invert_colors_off',
//   'iso',
//   'keyboard',
//   'keyboard_arrow_down',
//   'keyboard_arrow_left',
//   'keyboard_arrow_right',
//   'keyboard_arrow_up',
//   'keyboard_backspace',
//   'keyboard_capslock',
//   'keyboard_hide',
//   'keyboard_return',
//   'keyboard_tab',
//   'keyboard_voice',
//   'kitchen',
//   'label',
//   'label_outline',
//   'landscape',
//   'language',
//   'laptop',
//   'laptop_chromebook',
//   'laptop_mac',
//   'laptop_windows',
//   'last_page',
//   'launch',
//   'layers',
//   'layers_clear',
//   'leak_add',
//   'leak_remove',
//   'lens',
//   'library_add',
//   'library_books',
//   'library_music',
//   'lightbulb_outline',
//   'line_style',
//   'line_weight',
//   'linear_scale',
//   'link',
//   'linked_camera',
//   'list',
//   'live_help',
//   'live_tv',
//   'local_activity',
//   'local_airport',
//   'local_atm',
//   'local_bar',
//   'local_cafe',
//   'local_car_wash',
//   'local_convenience_store',
//   'local_dining',
//   'local_drink',
//   'local_florist',
//   'local_gas_station',
//   'local_grocery_store',
//   'local_hospital',
//   'local_hotel',
//   'local_laundry_service',
//   'local_library',
//   'local_mall',
//   'local_movies',
//   'local_offer',
//   'local_parking',
//   'local_pharmacy',
//   'local_phone',
//   'local_pizza',
//   'local_play',
//   'local_post_office',
//   'local_printshop',
//   'local_see',
//   'local_shipping',
//   'local_taxi',
//   'location_city',
//   'location_disabled',
//   'location_off',
//   'location_on',
//   'location_searching',
//   'lock',
//   'lock_open',
//   'lock_outline',
//   'looks',
//   'looks_3',
//   'looks_4',
//   'looks_5',
//   'looks_6',
//   'looks_one',
//   'looks_two',
//   'loop',
//   'loupe',
//   'low_priority',
//   'loyalty',
//   'mail',
//   'mail_outline',
//   'map',
//   'markunread',
//   'markunread_mailbox',
//   'memory',
//   'menu',
//   'merge_type',
//   'message',
//   'mic',
//   'mic_none',
//   'mic_off',
//   'mms',
//   'mode_comment',
//   'mode_edit',
//   'monetization_on',
//   'money_off',
//   'monochrome_photos',
//   'mood',
//   'mood_bad',
//   'more',
//   'more_horiz',
//   'more_vert',
//   'motorcycle',
//   'mouse',
//   'move_to_inbox',
//   'movie',
//   'movie_creation',
//   'movie_filter',
//   'multiline_chart',
//   'music_note',
//   'music_video',
//   'my_location',
//   'nature',
//   'nature_people',
//   'navigate_before',
//   'navigate_next',
//   'navigation',
//   'near_me',
//   'network_cell',
//   'network_check',
//   'network_locked',
//   'network_wifi',
//   'new_releases',
//   'next_week',
//   'nfc',
//   'no_encryption',
//   'no_sim',
//   'not_interested',
//   'note',
//   'note_add',
//   'notifications',
//   'notifications_active',
//   'notifications_none',
//   'notifications_off',
//   'notifications_paused',
//   'offline_pin',
//   'ondemand_video',
//   'opacity',
//   'open_in_browser',
//   'open_in_new',
//   'open_with',
//   'pages',
//   'pageview',
//   'palette',
//   'pan_tool',
//   'panorama',
//   'panorama_fish_eye',
//   'panorama_horizontal',
//   'panorama_vertical',
//   'panorama_wide_angle',
//   'party_mode',
//   'pause',
//   'pause_circle_filled',
//   'pause_circle_outline',
//   'payment',
//   'people',
//   'people_outline',
//   'perm_camera_mic',
//   'perm_contact_calendar',
//   'perm_data_setting',
//   'perm_device_information',
//   'perm_identity',
//   'perm_media',
//   'perm_phone_msg',
//   'perm_scan_wifi',
//   'person',
//   'person_add',
//   'person_outline',
//   'person_pin',
//   'person_pin_circle',
//   'personal_video',
//   'pets',
//   'phone',
//   'phone_android',
//   'phone_bluetooth_speaker',
//   'phone_forwarded',
//   'phone_in_talk',
//   'phone_iphone',
//   'phone_locked',
//   'phone_missed',
//   'phone_paused',
//   'phonelink',
//   'phonelink_erase',
//   'phonelink_lock',
//   'phonelink_off',
//   'phonelink_ring',
//   'phonelink_setup',
//   'photo',
//   'photo_album',
//   'photo_camera',
//   'photo_filter',
//   'photo_library',
//   'photo_size_select_actual',
//   'photo_size_select_large',
//   'photo_size_select_small',
//   'picture_as_pdf',
//   'picture_in_picture',
//   'picture_in_picture_alt',
//   'pie_chart',
//   'pie_chart_outlined',
//   'pin_drop',
//   'place',
//   'play_arrow',
//   'play_circle_filled',
//   'play_circle_outline',
//   'play_for_work',
//   'playlist_add',
//   'playlist_add_check',
//   'playlist_play',
//   'plus_one',
//   'poll',
//   'polymer',
//   'pool',
//   'portable_wifi_off',
//   'portrait',
//   'power',
//   'power_input',
//   'power_settings_new',
//   'pregnant_woman',
//   'present_to_all',
//   'print',
//   'priority_high',
//   'public',
//   'publish',
//   'query_builder',
//   'question_answer',
//   'queue',
//   'queue_music',
//   'queue_play_next',
//   'radio',
//   'radio_button_checked',
//   'radio_button_unchecked',
//   'rate_review',
//   'receipt',
//   'recent_actors',
//   'record_voice_over',
//   'redeem',
//   'redo',
//   'refresh',
//   'remove',
//   'remove_circle',
//   'remove_circle_outline',
//   'remove_from_queue',
//   'remove_red_eye',
//   'remove_shopping_cart',
//   'reorder',
//   'repeat',
//   'repeat_one',
//   'replay',
//   'replay_10',
//   'replay_30',
//   'replay_5',
//   'reply',
//   'reply_all',
//   'report',
//   'report_problem',
//   'restaurant',
//   'restaurant_menu',
//   'restore',
//   'restore_page',
//   'ring_volume',
//   'room',
//   'room_service',
//   'rotate_90_degrees_ccw',
//   'rotate_left',
//   'rotate_right',
//   'rounded_corner',
//   'router',
//   'rowing',
//   'rss_feed',
//   'rv_hookup',
//   'satellite',
//   'save',
//   'scanner',
//   'schedule',
//   'school',
//   'screen_lock_landscape',
//   'screen_lock_portrait',
//   'screen_lock_rotation',
//   'screen_rotation',
//   'screen_share',
//   'sd_card',
//   'sd_storage',
//   'search',
//   'security',
//   'select_all',
//   'send',
//   'sentiment_dissatisfied',
//   'sentiment_neutral',
//   'sentiment_satisfied',
//   'sentiment_very_dissatisfied',
//   'sentiment_very_satisfied',
//   'settings',
//   'settings_applications',
//   'settings_backup_restore',
//   'settings_bluetooth',
//   'settings_brightness',
//   'settings_cell',
//   'settings_ethernet',
//   'settings_input_antenna',
//   'settings_input_component',
//   'settings_input_composite',
//   'settings_input_hdmi',
//   'settings_input_svideo',
//   'settings_overscan',
//   'settings_phone',
//   'settings_power',
//   'settings_remote',
//   'settings_system_daydream',
//   'settings_voice',
//   'share',
//   'shop',
//   'shop_two',
//   'shopping_basket',
//   'shopping_cart',
//   'short_text',
//   'show_chart',
//   'shuffle',
//   'signal_cellular_4_bar',
//   'signal_cellular_connected_no_internet_4_bar',
//   'signal_cellular_no_sim',
//   'signal_cellular_null',
//   'signal_cellular_off',
//   'signal_wifi_4_bar',
//   'signal_wifi_4_bar_lock',
//   'signal_wifi_off',
//   'sim_card',
//   'sim_card_alert',
//   'skip_next',
//   'skip_previous',
//   'slideshow',
//   'slow_motion_video',
//   'smartphone',
//   'smoke_free',
//   'smoking_rooms',
//   'sms',
//   'sms_failed',
//   'snooze',
//   'sort',
//   'sort_by_alpha',
//   'spa',
//   'space_bar',
//   'speaker',
//   'speaker_group',
//   'speaker_notes',
//   'speaker_notes_off',
//   'speaker_phone',
//   'spellcheck',
//   'star',
//   'star_border',
//   'star_half',
//   'stars',
//   'stay_current_landscape',
//   'stay_current_portrait',
//   'stay_primary_landscape',
//   'stay_primary_portrait',
//   'stop',
//   'stop_screen_share',
//   'storage',
//   'store',
//   'store_mall_directory',
//   'straighten',
//   'streetview',
//   'strikethrough_s',
//   'style',
//   'subdirectory_arrow_left',
//   'subdirectory_arrow_right',
//   'subject',
//   'subscriptions',
//   'subtitles',
//   'subway',
//   'supervisor_account',
//   'surround_sound',
//   'swap_calls',
//   'swap_horiz',
//   'swap_vert',
//   'swap_vertical_circle',
//   'switch_camera',
//   'switch_video',
//   'sync',
//   'sync_disabled',
//   'sync_problem',
//   'system_update',
//   'system_update_alt',
//   'tab',
//   'tab_unselected',
//   'tablet',
//   'tablet_android',
//   'tablet_mac',
//   'tag_faces',
//   'tap_and_play',
//   'terrain',
//   'text_fields',
//   'text_format',
//   'textsms',
//   'texture',
//   'theaters',
//   'thumb_down',
//   'thumb_up',
//   'thumbs_up_down',
//   'time_to_leave',
//   'timelapse',
//   'timeline',
//   'timer',
//   'timer_10',
//   'timer_3',
//   'timer_off',
//   'title',
//   'toc',
//   'today',
//   'toll',
//   'tonality',
//   'touch_app',
//   'toys',
//   'track_changes',
//   'traffic',
//   'train',
//   'tram',
//   'transfer_within_a_station',
//   'transform',
//   'translate',
//   'trending_down',
//   'trending_flat',
//   'trending_up',
//   'tune',
//   'turned_in',
//   'turned_in_not',
//   'tv',
//   'unarchive',
//   'undo',
//   'unfold_less',
//   'unfold_more',
//   'update',
//   'usb',
//   'verified_user',
//   'vertical_align_bottom',
//   'vertical_align_center',
//   'vertical_align_top',
//   'vibration',
//   'video_call',
//   'video_label',
//   'video_library',
//   'videocam',
//   'videocam_off',
//   'videogame_asset',
//   'view_agenda',
//   'view_array',
//   'view_carousel',
//   'view_column',
//   'view_comfy',
//   'view_compact',
//   'view_day',
//   'view_headline',
//   'view_list',
//   'view_module',
//   'view_quilt',
//   'view_stream',
//   'view_week',
//   'vignette',
//   'visibility',
//   'visibility_off',
//   'voice_chat',
//   'voicemail',
//   'volume_down',
//   'volume_mute',
//   'volume_off',
//   'volume_up',
//   'vpn_key',
//   'vpn_lock',
//   'wallpaper',
//   'warning',
//   'watch',
//   'watch_later',
//   'wb_auto',
//   'wb_cloudy',
//   'wb_incandescent',
//   'wb_iridescent',
//   'wb_sunny',
//   'wc',
//   'web',
//   'web_asset',
//   'weekend',
//   'whatshot',
//   'widgets',
//   'wifi',
//   'wifi_lock',
//   'wifi_tethering',
//   'work',
//   'wrap_text',
//   'youtube_searched_for',
//   'zoom_in',
//   'zoom_out',
//   'zoom_out_map',
// ];

export const ICONS_NAMES = [
  '360',
  '3d_rotation',
  '4k',
  'ac_unit',
  'access_alarm',
  'access_time',
  'accessibility_new',
  'accessible',
  'account_balance',
  'account_balance_wallet',
  'account_box',
  'account_circle',
  'account_tree',
  'adb',
  'add',
  'add_a_photo',
  'add_alarm',
  'add_alert',
  'add_box',
  'add_circle',
  'add_circle_outline',
  'add_comment',
  'add_location',
  'add_photo_alternate',
  'add_shopping_cart',
  'add_to_home_screen',
  'add_to_photos',
  'add_to_queue',
  'adjust',
  'airline_seat_flat',
  'airline_seat_flat_angled',
  'airline_seat_individual_suite',
  'airline_seat_legroom_extra',
  'airline_seat_legroom_normal',
  'airline_seat_legroom_reduced',
  'airline_seat_recline_extra',
  'airline_seat_recline_normal',
  'airplanemode_active',
  'airplanemode_inactive',
  'airplay',
  'airport_shuttle',
  'alarm',
  'alarm_add',
  'alarm_off',
  'alarm_on',
  'album',
  'all_inbox',
  'all_inclusive',
  'all_out',
  'alternate_email',
  'amp_stories',
  'android',
  'announcement',
  'apartment',
  'apps',
  'archive',
  'arrow_back',
  'arrow_back_ios',
  'arrow_downward',
  'arrow_drop_down',
  'arrow_drop_down_circle',
  'arrow_drop_up',
  'arrow_forward',
  'arrow_forward_ios',
  'arrow_left',
  'arrow_right',
  'arrow_right_alt',
  'arrow_upward',
  'art_track',
  'aspect_ratio',
  'assessment',
  'assignment',
  'assignment_ind',
  'assignment_late',
  'assignment_return',
  'assignment_returned',
  'assignment_turned_in',
  'assistant',
  'assistant_photo',
  'atm',
  'attach_file',
  'attach_money',
  'attachment',
  'audiotrack',
  'autorenew',
  'av_timer',
  'backspace',
  'backup',
  'ballot',
  'bar_chart',
  'bathtub',
  'battery_alert',
  'battery_charging_full',
  'battery_full',
  'battery_std',
  'battery_unknown',
  'beach_access',
  'beenhere',
  'block',
  'bluetooth',
  'bluetooth_audio',
  'bluetooth_connected',
  'bluetooth_disabled',
  'bluetooth_searching',
  'blur_circular',
  'blur_linear',
  'blur_off',
  'blur_on',
  'book',
  'bookmark',
  'bookmark_border',
  'bookmarks',
  'border_all',
  'border_bottom',
  'border_clear',
  'border_color',
  'border_horizontal',
  'border_inner',
  'border_left',
  'border_outer',
  'border_right',
  'border_style',
  'border_top',
  'border_vertical',
  'branding_watermark',
  'brightness_1',
  'brightness_2',
  'brightness_3',
  'brightness_4',
  'brightness_5',
  'brightness_6',
  'brightness_7',
  'brightness_auto',
  'brightness_high',
  'brightness_low',
  'brightness_medium',
  'broken_image',
  'brush',
  'bubble_chart',
  'bug_report',
  'build',
  'burst_mode',
  'business',
  'business_center',
  'cached',
  'cake',
  'calendar_today',
  'calendar_view_day',
  'call',
  'call_end',
  'call_made',
  'call_merge',
  'call_missed',
  'call_missed_outgoing',
  'call_received',
  'call_split',
  'call_to_action',
  'camera',
  'camera_alt',
  'camera_enhance',
  'camera_front',
  'camera_rear',
  'camera_roll',
  'cancel',
  'cancel_presentation',
  'cancel_schedule_send',
  'card_giftcard',
  'card_membership',
  'card_travel',
  'casino',
  'cast',
  'cast_connected',
  'cast_for_education',
  'category',
  'cell_wifi',
  'center_focus_strong',
  'center_focus_weak',
  'change_history',
  'chat',
  'chat_bubble',
  'chat_bubble_outline',
  'check',
  'check_box',
  'check_box_outline_blank',
  'check_circle',
  'check_circle_outline',
  'chevron_left',
  'chevron_right',
  'child_care',
  'child_friendly',
  'chrome_reader_mode',
  'class',
  'clear',
  'clear_all',
  'close',
  'closed_caption',
  'cloud',
  'cloud_circle',
  'cloud_done',
  'cloud_download',
  'cloud_off',
  'cloud_queue',
  'cloud_upload',
  'code',
  'collections',
  'collections_bookmark',
  'color_lens',
  'colorize',
  'comment',
  'commute',
  'compare',
  'compare_arrows',
  'compass_calibration',
  'computer',
  'confirmation_number',
  'contact_mail',
  'contact_phone',
  'contact_support',
  'contactless',
  'contacts',
  'content_copy',
  'content_cut',
  'content_paste',
  'control_camera',
  'control_point',
  'control_point_duplicate',
  'copyright',
  'create',
  'create_new_folder',
  'credit_card',
  'crop',
  'crop_16_9',
  'crop_3_2',
  'crop_5_4',
  'crop_7_5',
  'crop_din',
  'crop_free',
  'crop_landscape',
  'crop_original',
  'crop_portrait',
  'crop_rotate',
  'crop_square',
  'dashboard',
  'data_usage',
  'date_range',
  'deck',
  'dehaze',
  'delete',
  'delete_forever',
  'delete_outline',
  'delete_sweep',
  'departure_board',
  'description',
  'desktop_access_disabled',
  'desktop_mac',
  'desktop_windows',
  'details',
  'developer_board',
  'developer_mode',
  'device_hub',
  'device_unknown',
  'devices',
  'devices_other',
  'dialer_sip',
  'dialpad',
  'directions',
  'directions_bike',
  'directions_boat',
  'directions_bus',
  'directions_car',
  'directions_railway',
  'directions_run',
  'directions_subway',
  'directions_transit',
  'directions_walk',
  'disc_full',
  'dns',
  'do_not_disturb',
  'do_not_disturb_alt',
  'do_not_disturb_off',
  'dock',
  'domain',
  'domain_disabled',
  'done',
  'done_all',
  'done_outline',
  'donut_large',
  'donut_small',
  'double_arrow',
  'drafts',
  'drag_handle',
  'drag_indicator',
  'drive_eta',
  'duo',
  'dvr',
  'dynamic_feed',
  'eco',
  'edit',
  'edit_attributes',
  'edit_location',
  'eject',
  'email',
  'emoji_emotions',
  'emoji_events',
  'emoji_flags',
  'emoji_food_beverage',
  'emoji_nature',
  'emoji_objects',
  'emoji_people',
  'emoji_symbols',
  'emoji_transportation',
  'enhanced_encryption',
  'equalizer',
  'error',
  'error_outline',
  'euro',
  'euro_symbol',
  'ev_station',
  'event',
  'event_available',
  'event_busy',
  'event_note',
  'event_seat',
  'exit_to_app',
  'expand_less',
  'expand_more',
  'explicit',
  'explore',
  'explore_off',
  'exposure',
  'exposure_neg_1',
  'exposure_neg_2',
  'exposure_plus_1',
  'exposure_plus_2',
  'exposure_zero',
  'extension',
  'face',
  'fast_forward',
  'fast_rewind',
  'fastfood',
  'favorite',
  'favorite_border',
  'featured_play_list',
  'featured_video',
  'feedback',
  'fiber_dvr',
  'fiber_manual_record',
  'fiber_new',
  'fiber_pin',
  'fiber_smart_record',
  'file_copy',
  'file_upload',
  'filter',
  'filter_1',
  'filter_2',
  'filter_3',
  'filter_4',
  'filter_5',
  'filter_6',
  'filter_7',
  'filter_8',
  'filter_9',
  'filter_9_plus',
  'filter_b_and_w',
  'filter_center_focus',
  'filter_drama',
  'filter_frames',
  'filter_hdr',
  'filter_list',
  'filter_none',
  'filter_tilt_shift',
  'filter_vintage',
  'find_in_page',
  'find_replace',
  'fingerprint',
  'fireplace',
  'first_page',
  'fitness_center',
  'flag',
  'flare',
  'flash_auto',
  'flash_off',
  'flash_on',
  'flight',
  'flight_land',
  'flight_takeoff',
  'flip',
  'flip_camera_android',
  'flip_camera_ios',
  'flip_to_back',
  'flip_to_front',
  'folder',
  'folder_open',
  'folder_shared',
  'folder_special',
  'font_download',
  'format_align_center',
  'format_align_justify',
  'format_align_left',
  'format_align_right',
  'format_bold',
  'format_clear',
  'format_color_fill',
  'format_color_reset',
  'format_color_text',
  'format_indent_decrease',
  'format_indent_increase',
  'format_italic',
  'format_line_spacing',
  'format_list_bulleted',
  'format_list_numbered',
  'format_list_numbered_rtl',
  'format_paint',
  'format_quote',
  'format_shapes',
  'format_size',
  'format_strikethrough',
  'format_textdirection_l_to_r',
  'format_textdirection_r_to_l',
  'format_underlined',
  'forum',
  'forward',
  'forward_10',
  'forward_30',
  'forward_5',
  'free_breakfast',
  'fullscreen',
  'fullscreen_exit',
  'functions',
  'g_translate',
  'gamepad',
  'games',
  'gavel',
  'gesture',
  'get_app',
  'gif',
  'golf_course',
  'gps_fixed',
  'gps_not_fixed',
  'gps_off',
  'grade',
  'gradient',
  'grain',
  'graphic_eq',
  'greater_than',
  'greater_than_equal',
  'grid_off',
  'grid_on',
  'group',
  'group_add',
  'group_work',
  'hd',
  'hdr_off',
  'hdr_on',
  'hdr_strong',
  'hdr_weak',
  'headset',
  'headset_mic',
  'healing',
  'hearing',
  'height',
  'help',
  'help_outline',
  'high_quality',
  'highlight',
  'highlight_off',
  'history',
  'home',
  'home_work',
  'horizontal_split',
  'hot_tub',
  'hotel',
  'hourglass_empty',
  'hourglass_full',
  'house',
  'how_to_reg',
  'how_to_vote',
  'http',
  'https',
  'image',
  'image_aspect_ratio',
  'image_search',
  'import_contacts',
  'import_export',
  'important_devices',
  'inbox',
  'indeterminate_check_box',
  'info',
  'input',
  'insert_chart',
  'insert_chart_outlined',
  'insert_comment',
  'insert_drive_file',
  'insert_emoticon',
  'insert_invitation',
  'insert_link',
  'insert_photo',
  'invert_colors',
  'invert_colors_off',
  'iso',
  'keyboard',
  'keyboard_arrow_down',
  'keyboard_arrow_left',
  'keyboard_arrow_right',
  'keyboard_arrow_up',
  'keyboard_backspace',
  'keyboard_capslock',
  'keyboard_hide',
  'keyboard_return',
  'keyboard_tab',
  'keyboard_voice',
  'king_bed',
  'kitchen',
  'label',
  'label_important',
  'label_off',
  'landscape',
  'language',
  'laptop',
  'laptop_chromebook',
  'laptop_mac',
  'laptop_windows',
  'last_page',
  'launch',
  'layers',
  'layers_clear',
  'leak_add',
  'leak_remove',
  'lens',
  'less_than',
  'less_than_equal',
  'library_add',
  'library_books',
  'library_music',
  'lightbulb',
  'line_style',
  'line_weight',
  'linear_scale',
  'link',
  'link_off',
  'linked_camera',
  'list',
  'list_alt',
  'live_help',
  'live_tv',
  'local_activity',
  'local_airport',
  'local_atm',
  'local_bar',
  'local_cafe',
  'local_car_wash',
  'local_convenience_store',
  'local_dining',
  'local_drink',
  'local_florist',
  'local_gas_station',
  'local_grocery_store',
  'local_hospital',
  'local_hotel',
  'local_laundry_service',
  'local_library',
  'local_mall',
  'local_movies',
  'local_offer',
  'local_parking',
  'local_pharmacy',
  'local_phone',
  'local_pizza',
  'local_play',
  'local_post_office',
  'local_printshop',
  'local_see',
  'local_shipping',
  'local_taxi',
  'location_city',
  'location_disabled',
  'location_off',
  'location_on',
  'location_searching',
  'lock',
  'lock_open',
  'log_in',
  'log_out',
  'looks',
  'looks_3',
  'looks_4',
  'looks_5',
  'looks_6',
  'looks_one',
  'looks_two',
  'loop',
  'loupe',
  'low_priority',
  'loyalty',
  'mail',
  'mail_outline',
  'map',
  'markunread',
  'markunread_mailbox',
  'maximize',
  'meeting_room',
  'memory',
  'menu',
  'menu_book',
  'menu_open',
  'merge_type',
  'message',
  'mic',
  'mic_none',
  'mic_off',
  'minimize',
  'minus',
  'missed_video_call',
  'mms',
  'mobile_friendly',
  'mobile_off',
  'mobile_screen_share',
  'mode_comment',
  'monetization_on',
  'money',
  'money_off',
  'monochrome_photos',
  'mood',
  'mood_bad',
  'more',
  'more_horiz',
  'more_vert',
  'motorcycle',
  'mouse',
  'move_to_inbox',
  'movie',
  'movie_creation',
  'movie_filter',
  'multiline_chart',
  'museum',
  'music_note',
  'music_off',
  'music_video',
  'my_location',
  'nature',
  'nature_people',
  'navigate_before',
  'navigate_next',
  'navigation',
  'near_me',
  'network_cell',
  'network_check',
  'network_locked',
  'network_wifi',
  'new_releases',
  'next_week',
  'nfc',
  'nights_stay',
  'no_encryption',
  'no_meeting_room',
  'no_sim',
  'not_equal',
  'not_interested',
  'not_listed_location',
  'note',
  'note_add',
  'notes',
  'notification_important',
  'notifications',
  'notifications_active',
  'notifications_none',
  'notifications_off',
  'notifications_paused',
  'offline_bolt',
  'offline_pin',
  'ondemand_video',
  'opacity',
  'open_in_browser',
  'open_in_new',
  'open_with',
  'outdoor_grill',
  'outlined_flag',
  'pages',
  'pageview',
  'palette',
  'pan_tool',
  'panorama',
  'panorama_fish_eye',
  'panorama_horizontal',
  'panorama_vertical',
  'panorama_wide_angle',
  'party_mode',
  'pause',
  'pause_circle_filled',
  'pause_circle_outline',
  'pause_presentation',
  'payment',
  'people',
  'people_alt',
  'people_outline',
  'percentage',
  'perm_camera_mic',
  'perm_contact_calendar',
  'perm_data_setting',
  'perm_device_information',
  'perm_identity',
  'perm_media',
  'perm_phone_msg',
  'perm_scan_wifi',
  'person',
  'person_add',
  'person_add_disabled',
  'person_outline',
  'person_pin',
  'person_pin_circle',
  'personal_video',
  'pets',
  'phone',
  'phone_android',
  'phone_bluetooth_speaker',
  'phone_callback',
  'phone_disabled',
  'phone_enabled',
  'phone_forwarded',
  'phone_in_talk',
  'phone_iphone',
  'phone_locked',
  'phone_missed',
  'phone_paused',
  'phonelink',
  'phonelink_erase',
  'phonelink_lock',
  'phonelink_off',
  'phonelink_ring',
  'phonelink_setup',
  'photo',
  'photo_album',
  'photo_camera',
  'photo_filter',
  'photo_library',
  'photo_size_select_actual',
  'photo_size_select_large',
  'photo_size_select_small',
  'picture_as_pdf',
  'picture_in_picture',
  'picture_in_picture_alt',
  'pie_chart',
  'pin',
  'pin_drop',
  'pin_off',
  'place',
  'play_arrow',
  'play_circle_filled',
  'play_circle_filled_white',
  'play_circle_outline',
  'play_for_work',
  'playlist_add',
  'playlist_add_check',
  'playlist_play',
  'plus',
  'plus_minus',
  'plus_minus_alt',
  'plus_one',
  'policy',
  'poll',
  'polymer',
  'pool',
  'portable_wifi_off',
  'portrait',
  'post_add',
  'power',
  'power_input',
  'power_off',
  'power_settings_new',
  'pregnant_woman',
  'present_to_all',
  'print',
  'print_disabled',
  'priority_high',
  'public',
  'publish',
  'query_builder',
  'question_answer',
  'queue',
  'queue_music',
  'queue_play_next',
  'radio',
  'radio_button_checked',
  'radio_button_unchecked',
  'rate_review',
  'receipt',
  'recent_actors',
  'record_voice_over',
  'redeem',
  'redo',
  'refresh',
  'remove',
  'remove_circle',
  'remove_circle_outline',
  'remove_from_queue',
  'remove_red_eye',
  'remove_shopping_cart',
  'reorder',
  'repeat',
  'repeat_one',
  'replay',
  'replay_10',
  'replay_30',
  'replay_5',
  'reply',
  'reply_all',
  'report',
  'report_off',
  'report_problem',
  'restaurant',
  'restaurant_menu',
  'restore',
  'restore_from_trash',
  'restore_page',
  'ring_volume',
  'rocket',
  'room',
  'room_service',
  'rotate_90_degrees_ccw',
  'rotate_left',
  'rotate_right',
  'rounded_corner',
  'router',
  'rowing',
  'rss_feed',
  'rv_hookup',
  'satellite',
  'save',
  'save_alt',
  'scanner',
  'scatter_plot',
  'schedule',
  'school',
  'score',
  'screen_lock_landscape',
  'screen_lock_portrait',
  'screen_lock_rotation',
  'screen_rotation',
  'screen_share',
  'sd_card',
  'sd_storage',
  'search',
  'security',
  'select_all',
  'send',
  'sentiment_dissatisfied',
  'sentiment_neutral',
  'sentiment_satisfied',
  'sentiment_satisfied_alt',
  'sentiment_slightly_dissatisfied',
  'sentiment_very_dissatisfied',
  'sentiment_very_satisfied',
  'settings',
  'settings_applications',
  'settings_backup_restore',
  'settings_bluetooth',
  'settings_brightness',
  'settings_cell',
  'settings_ethernet',
  'settings_input_antenna',
  'settings_input_component',
  'settings_input_composite',
  'settings_input_hdmi',
  'settings_input_svideo',
  'settings_overscan',
  'settings_phone',
  'settings_power',
  'settings_remote',
  'settings_system_daydream',
  'settings_voice',
  'share',
  'shop',
  'shop_two',
  'shopping_basket',
  'shopping_cart',
  'short_text',
  'show_chart',
  'shuffle',
  'shutter_speed',
  'signal_cellular_0_bar',
  'signal_cellular_1_bar',
  'signal_cellular_2_bar',
  'signal_cellular_3_bar',
  'signal_cellular_4_bar',
  'signal_cellular_alt',
  'signal_cellular_connected_no_internet_0_bar',
  'signal_cellular_connected_no_internet_1_bar',
  'signal_cellular_connected_no_internet_2_bar',
  'signal_cellular_connected_no_internet_3_bar',
  'signal_cellular_connected_no_internet_4_bar',
  'signal_cellular_no_sim',
  'signal_cellular_null',
  'signal_cellular_off',
  'signal_wifi_0_bar',
  'signal_wifi_1_bar',
  'signal_wifi_1_bar_lock',
  'signal_wifi_2_bar',
  'signal_wifi_2_bar_lock',
  'signal_wifi_3_bar',
  'signal_wifi_3_bar_lock',
  'signal_wifi_4_bar',
  'signal_wifi_4_bar_lock',
  'signal_wifi_off',
  'sim_card',
  'single_bed',
  'skip_next',
  'skip_previous',
  'slideshow',
  'slow_motion_video',
  'smartphone',
  'smoke_free',
  'smoking_rooms',
  'sms',
  'sms_failed',
  'snooze',
  'sort',
  'sort_by_alpha',
  'spa',
  'space_bar',
  'speaker',
  'speaker_group',
  'speaker_notes',
  'speaker_notes_off',
  'speaker_phone',
  'speed',
  'spellcheck',
  'sports',
  'sports_baseball',
  'sports_basketball',
  'sports_cricket',
  'sports_esports',
  'sports_football',
  'sports_golf',
  'sports_handball',
  'sports_hockey',
  'sports_kabaddi',
  'sports_mma',
  'sports_motorsports',
  'sports_rugby',
  'sports_soccer',
  'sports_tennis',
  'sports_volleyball',
  'square_foot',
  'star',
  'star_border',
  'star_half',
  'star_rate',
  'stars',
  'stay_current_landscape',
  'stay_current_portrait',
  'stay_primary_landscape',
  'stay_primary_portrait',
  'stop',
  'stop_circle',
  'stop_screen_share',
  'storage',
  'store',
  'store_mall_directory',
  'storefront',
  'straighten',
  'streetview',
  'strikethrough_s',
  'style',
  'subdirectory_arrow_left',
  'subdirectory_arrow_right',
  'subject',
  'subscriptions',
  'subtitles',
  'subway',
  'supervised_user_circle',
  'supervisor_account',
  'surround_sound',
  'swap_calls',
  'swap_horiz',
  'swap_horizontal_circle',
  'swap_vert',
  'swap_vertical_circle',
  'switch_camera',
  'switch_video',
  'sync',
  'sync_alt',
  'sync_disabled',
  'sync_problem',
  'system_update',
  'system_update_alt',
  'tab',
  'tab_unselected',
  'table_chart',
  'tablet',
  'tablet_android',
  'tablet_mac',
  'tag_faces',
  'tap_and_play',
  'terrain',
  'text_fields',
  'text_format',
  'text_rotate_up',
  'text_rotate_vertical',
  'text_rotation_angledown',
  'text_rotation_angleup',
  'text_rotation_down',
  'text_rotation_none',
  'textsms',
  'texture',
  'theaters',
  'thumb_down',
  'thumb_down_alt',
  'thumb_up',
  'thumb_up_alt',
  'thumbs_up_down',
  'time_to_leave',
  'timelapse',
  'timeline',
  'timer',
  'timer_10',
  'timer_3',
  'timer_off',
  'title',
  'toc',
  'today',
  'toggle_off',
  'toggle_on',
  'toll',
  'tonality',
  'touch_app',
  'toys',
  'track_changes',
  'traffic',
  'train',
  'tram',
  'transfer_within_a_station',
  'transform',
  'transit_enterexit',
  'translate',
  'trending_down',
  'trending_flat',
  'trending_up',
  'trip_origin',
  'tune',
  'turned_in',
  'turned_in_not',
  'tv',
  'tv_off',
  'unarchive',
  'undo',
  'unfold_less',
  'unfold_more',
  'unsubscribe',
  'update',
  'usb',
  'verified_user',
  'vertical_align_bottom',
  'vertical_align_center',
  'vertical_align_top',
  'vertical_split',
  'vibration',
  'video_call',
  'video_label',
  'video_library',
  'videocam',
  'videocam_off',
  'videogame_asset',
  'view_agenda',
  'view_array',
  'view_carousel',
  'view_column',
  'view_comfy',
  'view_compact',
  'view_day',
  'view_headline',
  'view_list',
  'view_module',
  'view_quilt',
  'view_stream',
  'view_week',
  'vignette',
  'visibility',
  'visibility_off',
  'voice_chat',
  'voice_over_off',
  'voicemail',
  'volume_down',
  'volume_mute',
  'volume_off',
  'volume_up',
  'vpn_key',
  'vpn_lock',
  'wallpaper',
  'warning',
  'watch',
  'watch_later',
  'waves',
  'wb_auto',
  'wb_cloudy',
  'wb_incandescent',
  'wb_iridescent',
  'wb_sunny',
  'wc',
  'web',
  'web_asset',
  'weekend',
  'whatshot',
  'where_to_vote',
  'widgets',
  'wifi',
  'wifi_lock',
  'wifi_off',
  'wifi_tethering',
  'work',
  'work_off',
  'work_outline',
  'wrap_text',
  'youtube_searched_for',
  'zoom_in',
  'zoom_out',
  'zoom_out_map',
  'add_ic_call',
  'library_add_check',
  'star_outline',
  'two_wheeler',
  '5g',
  'ad_units',
  'add_business',
  'add_location_alt',
  'add_road',
  'addchart',
  'admin_panel_settings',
  'agriculture',
  'alt_route',
  'analytics',
  'anchor',
  'api',
  'app_blocking',
  'app_settings_alt',
  'architecture',
  'arrow_circle_down',
  'arrow_circle_up',
  'article',
  'attach_email',
  'auto_delete',
  'baby_changing_station',
  'backpack',
  'backup_table',
  'batch_prediction',
  'bedtime',
  'bike_scooter',
  'biotech',
  'browser_not_supported',
  'build_circle',
  'calculate',
  'campaign',
  'charging_station',
  'checkroom',
  'cleaning_services',
  'close_fullscreen',
  'comment_bank',
  'construction',
  'corporate_fare',
  'design_services',
  'directions_off',
  'do_not_step',
  'do_not_touch',
  'domain_verification',
  'dry',
  'dynamic_form',
  'edit_road',
  'electric_bike',
  'electric_car',
  'electric_moped',
  'electric_scooter',
  'electrical_services',
  'elevator',
  'engineering',
  'escalator',
  'escalator_warning',
  'fact_check',
  'family_restroom',
  'filter_alt',
  'flaky',
  'forward_to_inbox',
  'grading',
  'handyman',
  'hearing_disabled',
  'help_center',
  'highlight_alt',
  'history_edu',
  'history_toggle_off',
  'home_repair_service',
  'horizontal_rule',
  'hourglass_bottom',
  'hourglass_disabled',
  'hourglass_top',
  'hvac',
  'image_not_supported',
  'insights',
  'integration_instructions',
  'legend_toggle',
  'login',
  'maps_ugc',
  'mark_chat_read',
  'mark_chat_unread',
  'mark_email_read',
  'mark_email_unread',
  'mediation',
  'medical_services',
  'military_tech',
  'miscellaneous_services',
  'model_training',
  'moped',
  'more_time',
  'multiple_stop',
  'nat',
  'next_plan',
  'no_cell',
  'no_drinks',
  'no_flash',
  'no_food',
  'no_photography',
  'no_stroller',
  'not_accessible',
  'not_started',
  'online_prediction',
  'open_in_full',
  'outlet',
  'payments',
  'pedal_bike',
  'pending',
  'pending_actions',
  'person_add_alt_1',
  'person_remove',
  'person_remove_alt_1',
  'person_search',
  'pest_control',
  'pest_control_rodent',
  'plagiarism',
  'plumbing',
  'point_of_sale',
  'preview',
  'privacy_tip',
  'psychology',
  'public_off',
  'push_pin',
  'qr_code',
  'quickreply',
  'read_more',
  'receipt_long',
  'request_quote',
  'room_preferences',
  'rule',
  'rule_folder',
  'run_circle',
  'science',
  'search_off',
  'self_improvement',
  'sensor_door',
  'sensor_window',
  'shopping_bag',
  'smart_button',
  'snippet_folder',
  'soap',
  'source',
  'stairs',
  'stroller',
  'subscript',
  'subtitles_off',
  'superscript',
  'support',
  'support_agent',
  'switch_left',
  'switch_right',
  'table_rows',
  'table_view',
  'text_snippet',
  'topic',
  'tour',
  'tty',
  'umbrella',
  'upgrade',
  'verified',
  'video_settings',
  'view_sidebar',
  'wash',
  'wheelchair_pickup',
  'wifi_calling',
  'wifi_protected_setup',
  'wrong_location',
  'wysiwyg',
  'bento',
  'carpenter',
  'closed_caption_disabled',
  'countertops',
  'east',
  'fence',
  'fire_extinguisher',
  'food_bank',
  'foundation',
  'grass',
  'house_siding',
  'leaderboard',
  'microwave',
  'near_me_disabled',
  'night_shelter',
  'no_meals',
  'no_transfer',
  'north',
  'north_east',
  'north_west',
  'rice_bowl',
  'roofing',
  'set_meal',
  'south',
  'south_east',
  'south_west',
  'sports_bar',
  'sticky_note_2',
  'tapas',
  'water_damage',
  'west',
  'wine_bar',
  '6_ft_apart',
  'book_online',
  'clean_hands',
  'connect_without_contact',
  'coronavirus',
  'elderly',
  'follow_the_signs',
  'leave_bags_at_home',
  'local_fire_department',
  'local_police',
  'masks',
  'motion_photos_on',
  'motion_photos_paused',
  'reduce_capacity',
  'sanitizer',
  'sick',
  'add_task',
  'contact_page',
  'disabled_by_default',
  'facebook',
  'groups',
  'luggage',
  'motion_photos_pause',
  'no_backpack',
  'no_luggage',
  'outbond',
  'published_with_changes',
  'request_page',
  'stacked_line_chart',
  'unpublished',
  'align_horizontal_center',
  'align_horizontal_left',
  'align_horizontal_right',
  'align_vertical_bottom',
  'align_vertical_center',
  'align_vertical_top',
  'horizontal_distribute',
  'update_disabled',
  'vertical_distribute',
  'add_reaction',
  'add_to_drive',
  'arrow_back_ios_new',
  'change_circle',
  'copy_all',
  'electric_rickshaw',
  'health_and_safety',
  'outbound',
  'production_quantity_limits',
  'safety_divider',
  'savings',
  'social_distance',
  'task_alt',
  'travel_explore',
  'auto_graph',
  'catching_pokemon',
  'code_off',
  'content_paste_off',
  'dark_mode',
  'developer_board_off',
  'downhill_skiing',
  'edit_location_alt',
  'edit_notifications',
  'extension_off',
  'file_download_off',
  'flutter_dash',
  'font_download_off',
  'hiking',
  'ice_skating',
  'inventory_2',
  'kayaking',
  'kitesurfing',
  'light_mode',
  'moving',
  'nordic_walking',
  'notification_add',
  'open_in_new_off',
  'paragliding',
  'pause_circle',
  'person_off',
  'piano',
  'piano_off',
  'play_circle',
  'query_stats',
  'running_with_errors',
  'sailing',
  'schema',
  'sensors',
  'sensors_off',
  'share_arrival_time',
  'shop_2',
  'skateboarding',
  'sledding',
  'snowboarding',
  'snowmobile',
  'snowshoeing',
  'surfing',
  'usb_off',
  'videogame_asset_off',
  'wb_twilight',
  'web_asset_off',
  'workspaces',
  '10k',
  '10mp',
  '11mp',
  '12mp',
  '13mp',
  '14mp',
  '15mp',
  '16mp',
  '17mp',
  '18mp',
  '19mp',
  '1k',
  '1k_plus',
  '1x_mobiledata',
  '20mp',
  '21mp',
  '22mp',
  '23mp',
  '24mp',
  '2k',
  '2k_plus',
  '2mp',
  '30fps',
  '30fps_select',
  '3g_mobiledata',
  '3k',
  '3k_plus',
  '3mp',
  '3p',
  '4g_mobiledata',
  '4g_plus_mobiledata',
  '4k_plus',
  '4mp',
  '5k',
  '5k_plus',
  '5mp',
  '60fps',
  '60fps_select',
  '6k',
  '6k_plus',
  '6mp',
  '7k',
  '7k_plus',
  '7mp',
  '8k',
  '8k_plus',
  '8mp',
  '9k',
  '9k_plus',
  '9mp',
  'access_time_filled',
  'add_chart',
  'add_link',
  'add_moderator',
  'air',
  'airplane_ticket',
  'animation',
  'aod',
  'app_registration',
  'approval',
  'assistant_direction',
  'attractions',
  'attribution',
  'auto_awesome',
  'auto_awesome_mosaic',
  'auto_awesome_motion',
  'auto_fix_high',
  'auto_fix_normal',
  'auto_fix_off',
  'auto_stories',
  'autofps_select',
  'badge',
  'bakery_dining',
  'balcony',
  'bathroom',
  'battery_saver',
  'bed',
  'bedroom_baby',
  'bedroom_child',
  'bedroom_parent',
  'blender',
  'bloodtype',
  'bluetooth_drive',
  'bolt',
  'bookmark_add',
  'bookmark_added',
  'bookmark_remove',
  'breakfast_dining',
  'brunch_dining',
  'bungalow',
  'bus_alert',
  'cabin',
  'cable',
  'calendar_view_month',
  'calendar_view_week',
  'camera_indoor',
  'camera_outdoor',
  'cameraswitch',
  'car_rental',
  'car_repair',
  'cases',
  'celebration',
  'chair',
  'chair_alt',
  'chalet',
  'circle',
  'circle_notifications',
  'closed_caption_off',
  'coffee',
  'coffee_maker',
  'compress',
  'connected_tv',
  'cottage',
  'credit_score',
  'crib',
  'dangerous',
  'dashboard_customize',
  'data_saver_off',
  'data_saver_on',
  'delivery_dining',
  'device_thermostat',
  'dining',
  'dinner_dining',
  'directions_boat_filled',
  'directions_bus_filled',
  'directions_car_filled',
  'directions_railway_filled',
  'directions_subway_filled',
  'directions_transit_filled',
  'dirty_lens',
  'do_disturb',
  'do_disturb_alt',
  'do_disturb_off',
  'do_disturb_on',
  'do_not_disturb_on',
  'do_not_disturb_on_total_silence',
  'door_back',
  'door_front',
  'door_sliding',
  'doorbell',
  'download',
  'download_done',
  'download_for_offline',
  'downloading',
  'drive_file_move',
  'drive_file_rename_outline',
  'drive_folder_upload',
  'dry_cleaning',
  'e_mobiledata',
  'earbuds',
  'earbuds_battery',
  'edgesensor_high',
  'edgesensor_low',
  'edit_off',
  'expand',
  'face_retouching_natural',
  'face_retouching_off',
  'feed',
  'female',
  'festival',
  'file_download',
  'file_download_done',
  'file_present',
  'fit_screen',
  'flashlight_off',
  'flashlight_on',
  'flatware',
  'flourescent',
  'fmd_bad',
  'fmd_good',
  'g_mobiledata',
  'garage',
  'gite',
  'gpp_bad',
  'gpp_good',
  'gpp_maybe',
  'grid_3x3',
  'grid_4x4',
  'grid_goldenratio',
  'grid_view',
  'h_mobiledata',
  'h_plus_mobiledata',
  'hail',
  'hardware',
  'hdr_auto',
  'hdr_auto_select',
  'hdr_enhanced_select',
  'hdr_off_select',
  'hdr_on_select',
  'hdr_plus',
  'headphones',
  'headphones_battery',
  'headset_off',
  'hevc',
  'hide_image',
  'hide_source',
  'holiday_village',
  'home_max',
  'home_mini',
  'houseboat',
  'icecream',
  'imagesearch_roller',
  'inventory',
  'ios_share',
  'iron',
  'keyboard_alt',
  'lens_blur',
  'light',
  'liquor',
  'living',
  'lock_clock',
  'logout',
  'lte_mobiledata',
  'lte_plus_mobiledata',
  'lunch_dining',
  'male',
  'manage_accounts',
  'manage_search',
  'maps_home_work',
  'margin',
  'mark_as_unread',
  'media_bluetooth_off',
  'media_bluetooth_on',
  'medication',
  'mic_external_off',
  'mic_external_on',
  'mobiledata_off',
  'mode',
  'mode_edit',
  'mode_edit_outline',
  'mode_night',
  'mode_standby',
  'money_off_csred',
  'monitor',
  'monitor_weight',
  'motion_photos_auto',
  'motion_photos_off',
  'mp',
  'nearby_error',
  'nearby_off',
  'nightlife',
  'nightlight',
  'nightlight_round',
  'no_accounts',
  'no_encryption_gmailerrorred',
  'note_alt',
  'offline_share',
  'other_houses',
  'outbox',
  'padding',
  'paid',
  'panorama_horizontal_select',
  'panorama_photosphere',
  'panorama_photosphere_select',
  'panorama_vertical_select',
  'panorama_wide_angle_select',
  'park',
  'password',
  'pattern',
  'person_add_alt',
  'photo_camera_back',
  'photo_camera_front',
  'pie_chart_outline',
  'pivot_table_chart',
  'play_disabled',
  'play_lesson',
  'podcasts',
  'precision_manufacturing',
  'price_change',
  'price_check',
  'quiz',
  'r_mobiledata',
  'radar',
  'railway_alert',
  'ramen_dining',
  'raw_off',
  'raw_on',
  'recommend',
  'remember_me',
  'remove_done',
  'remove_moderator',
  'repeat_on',
  'repeat_one_on',
  'replay_circle_filled',
  'report_gmailerrorred',
  'reset_tv',
  'restart_alt',
  'reviews',
  'rsvp',
  'rtt',
  'saved_search',
  'schedule_send',
  'screen_search_desktop',
  'screenshot',
  'sd',
  'security_update',
  'security_update_good',
  'security_update_warning',
  'segment',
  'sell',
  'send_and_archive',
  'send_to_mobile',
  'settings_accessibility',
  'settings_suggest',
  'share_location',
  'shield',
  'shortcut',
  'shower',
  'shuffle_on',
  'signal_cellular_nodata',
  'signal_wifi_bad',
  'signal_wifi_connected_no_internet_4',
  'signal_wifi_statusbar_4_bar',
  'signal_wifi_statusbar_connected_no_internet_4',
  'signal_wifi_statusbar_null',
  'sip',
  'smart_display',
  'smart_screen',
  'smart_toy',
  'splitscreen',
  'sports_score',
  'stacked_bar_chart',
  'star_border_purple500',
  'star_purple500',
  'storm',
  'stream',
  'summarize',
  'swipe',
  'switch_account',
  'system_security_update',
  'system_security_update_good',
  'system_security_update_warning',
  'tag',
  'takeout_dining',
  'task',
  'taxi_alert',
  'theater_comedy',
  'thermostat',
  'thermostat_auto',
  'thumb_down_off_alt',
  'thumb_up_off_alt',
  'timer_10_select',
  'timer_3_select',
  'transgender',
  'try',
  'tungsten',
  'upcoming',
  'upload',
  'upload_file',
  'video_camera_back',
  'video_camera_front',
  'video_stable',
  'view_in_ar',
  'villa',
  'volunteer_activism',
  'vrpano',
  'warning_amber',
  'water',
  'waterfall_chart',
  'wb_shade',
  'wifi_calling_3',
  'wifi_tethering_error_rounded',
  'wifi_tethering_off',
  'window',
  'yard',
  'ads_click',
  'area_chart',
  'back_hand',
  'checklist',
  'checklist_rtl',
  'compost',
  'cruelty_free',
  'data_exploration',
  'disabled_visible',
  'document_scanner',
  'draw',
  'drive_file_move_rtl',
  'edit_calendar',
  'edit_note',
  'emergency',
  'free_cancellation',
  'front_hand',
  'generating_tokens',
  'group_off',
  'hotel_class',
  'incomplete_circle',
  'new_label',
  'personal_injury',
  'pin_end',
  'pin_invoke',
  'private_connectivity',
  'real_estate_agent',
  'recycling',
  'space_dashboard',
  'tips_and_updates',
  'water_drop',
  'waving_hand',
  'airline_stops',
  'airlines',
  'apps_outage',
  'browser_updated',
  'co2',
  'comments_disabled',
  'connecting_airports',
  'expand_circle_down',
  'flight_class',
  'gif_box',
  'group_remove',
  'interests',
  'mode_of_travel',
  'soup_kitchen',
  'workspace_premium',
  'switch_access_shortcut',
  'switch_access_shortcut_add',
  'interpreter_mode',
  'playlist_add_check_circle',
  'playlist_add_circle',
  'south_america',
  'vaccines',
  'adobe',
  'apple',
  'arrow_circle_left',
  'arrow_circle_right',
  'castle',
  'church',
  'content_paste_go',
  'content_paste_search',
  'cookie',
  'discord',
  'fitbit',
  'forest',
  'fort',
  'hive',
  'hub',
  'kebab_dining',
  'line_axis',
  'medication_liquid',
  'monitor_heart',
  'mosque',
  'paypal',
  'pix',
  'punch_clock',
  'quora',
  'reddit',
  'rotate_90_degrees_cw',
  'shield_moon',
  'shopify',
  'snapchat',
  'spoke',
  'synagogue',
  'telegram',
  'temple_buddhist',
  'temple_hindu',
  'tiktok',
  'token',
  'wechat',
  'whatsapp',
  'woo_commerce',
  'wordpress',
  'adf_scanner',
  'candlestick_chart',
  'data_array',
  'data_object',
  'diamond',
  'egg',
  'egg_alt',
  'fax',
  'heart_broken',
  'insert_page_break',
  'key',
  'keyboard_double_arrow_down',
  'keyboard_double_arrow_left',
  'keyboard_double_arrow_right',
  'keyboard_double_arrow_up',
  'logo_dev',
  'man',
  'numbers',
  'phishing',
  'route',
  'table_bar',
  'table_restaurant',
  'wifi_tethering_error',
  'woman',
  'send_time_extension',
  'app_shortcut',
  'balance',
  'cloud_sync',
  'co_present',
  'commit',
  'contrast',
  'currency_franc',
  'currency_lira',
  'currency_pound',
  'currency_ruble',
  'currency_rupee',
  'currency_yen',
  'currency_yuan',
  'file_open',
  'filter_alt_off',
  'filter_list_off',
  'flag_circle',
  'folder_delete',
  'folder_zip',
  'hexagon',
  'join_full',
  'join_inner',
  'join_left',
  'join_right',
  'keyboard_command_key',
  'keyboard_control_key',
  'keyboard_option_key',
  'lan',
  'lock_reset',
  'pentagon',
  'percent',
  'pinch',
  'rectangle',
  'satellite_alt',
  'sports_martial_arts',
  'square',
  'start',
  'swipe_down',
  'swipe_down_alt',
  'swipe_left',
  'swipe_left_alt',
  'swipe_right',
  'swipe_right_alt',
  'swipe_up',
  'swipe_up_alt',
  'swipe_vertical',
  'sync_lock',
  'text_decrease',
  'text_increase',
  'watch_off',
  'wifi_find',
  'zoom_in_map',
  'assured_workload',
  'bedtime_off',
  'boy',
  'currency_exchange',
  'deblur',
  'domain_add',
  'elderly_woman',
  'format_overline',
  'girl',
  'install_desktop',
  'install_mobile',
  'move_down',
  'move_up',
  'save_as',
  'scale',
  'ssid_chart',
  'view_comfy_alt',
  'view_compact_alt',
  'view_cozy',
  'wifi_channel',
  'wifi_password',
  '123',
  'abc',
  'audio_file',
  'css',
  'difference',
  'event_repeat',
  'folder_off',
  'hls',
  'hls_off',
  'html',
  'javascript',
  'key_off',
  'newspaper',
  'php',
  'playlist_remove',
  'question_mark',
  'shopping_cart_checkout',
  'signpost',
  'stadium',
  'terminal',
  'video_file',
  'view_kanban',
  'view_timeline',
  'vpn_key_off',
  'webhook',
  'cell_tower',
  'data_thresholding',
  'density_large',
  'density_medium',
  'density_small',
  'deselect',
  'display_settings',
  'factory',
  'fork_left',
  'fork_right',
  'mark_unread_chat_alt',
  'merge',
  'pan_tool_alt',
  'polyline',
  'ramp_left',
  'ramp_right',
  'rocket_launch',
  'roundabout_left',
  'roundabout_right',
  'straight',
  'turn_left',
  'turn_right',
  'turn_sharp_left',
  'turn_sharp_right',
  'turn_slight_left',
  'turn_slight_right',
  'u_turn_left',
  'u_turn_right',
  'warehouse',
  'save_all',
  'browse_gallery',
  'calendar_month',
  'currency_bitcoin',
  'discount',
  'folder_copy',
  'handshake',
  'network_ping',
  'output',
  'roller_skating',
  'scoreboard',
  'scuba_diving',
  'sports_gymnastics',
  'tire_repair',
  'vape_free',
  'vaping_rooms',
  'battery_0_bar',
  'battery_1_bar',
  'battery_2_bar',
  'battery_3_bar',
  'battery_4_bar',
  'battery_5_bar',
  'battery_6_bar',
  'car_crash',
  'crisis_alert',
  'cyclone',
  'devices_fold',
  'emergency_recording',
  'emergency_share',
  'flood',
  'landslide',
  'lightbulb_circle',
  'manage_history',
  'medical_information',
  'minor_crash',
  'network_wifi_1_bar',
  'network_wifi_2_bar',
  'network_wifi_3_bar',
  'no_crash',
  'noise_aware',
  'noise_control_off',
  'on_device_training',
  'remove_road',
  'safety_check',
  'screen_rotation_alt',
  'severe_cold',
  'sign_language',
  'signal_cellular_alt_1_bar',
  'signal_cellular_alt_2_bar',
  'sos',
  'spatial_audio',
  'spatial_audio_off',
  'spatial_tracking',
  'thunderstorm',
  'tsunami',
  'volcano',
  'wifi_1_bar',
  'wifi_2_bar',
  'auto_mode',
  'blinds_closed',
  'curtains',
  'curtains_closed',
  'electric_bolt',
  'electric_meter',
  'energy_savings_leaf',
  'gas_meter',
  'heat_pump',
  'lyrics',
  'mail_lock',
  'mode_fan_off',
  'nest_cam_wired_stand',
  'oil_barrel',
  'propane',
  'propane_tank',
  'roller_shades',
  'roller_shades_closed',
  'screenshot_monitor',
  'sensor_occupied',
  'solar_power',
  'tornado',
  'vertical_shades',
  'vertical_shades_closed',
  'wind_power',
  'work_history',
  '18_up_rating',
  'blinds',
  'broadcast_on_home',
  'broadcast_on_personal',
  'desk',
  'lock_person',
  'no_adult_content',
  'wallet',
  'width_full',
  'width_normal',
  'width_wide',
  'add_home',
  'add_home_work',
  'arrow_outward',
  'assist_walker',
  'blind',
  'contact_emergency',
  'dataset',
  'dataset_linked',
  'diversity_1',
  'diversity_2',
  'diversity_3',
  'face_2',
  'face_3',
  'face_4',
  'face_5',
  'face_6',
  'fire_hydrant_alt',
  'fire_truck',
  'groups_2',
  'groups_3',
  'macro_off',
  'man_2',
  'man_3',
  'man_4',
  'person_2',
  'person_3',
  'person_4',
  'psychology_alt',
  'repartition',
  'shape_line',
  'transcribe',
  'troubleshoot',
  'type_specimen',
  'unfold_less_double',
  'unfold_more_double',
  'web_stories',
  'woman_2',
  'fluorescent',
  'video_chat',
];

export const COLORS = [
  '#facfde', // Lighter Pink
  '#d6daf0', // Lighter Indigo
  '#ffdbd0', // Lighter Deep Orange
  '#e6f2d8', // Lighter Light Green
  '#fffbd6', // Lighter Yellow
  '#caedfd', // Lighter Light Blue
  '#fff2ca', // Lighter Amber
  '#dfd6f0', // Lighter Deep Purple
  '#f4f7d5', // Lighter Lime
  '#ffdce0', // Lighter Red
];

export const getIcons = (): IIcon[] => {
  let count = -1;
  const icons = ICONS_NAMES.map((item) => {
    count++;
    if (count >= 10) {
      count = 0;
    }
    const icon: IIcon = {
      name: item,
      label: item.split('_').join(' '),
      bgColor: COLORS[count],
    };
    return icon;
  });
  return icons;
};
